# -*- coding: utf-8 -*-
"""Descriptive Statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m87GQ-vVJDFbnWmgd88Su--G7d0HzDWY

## Práctica 2: Descriptive Statistics

Realizar un análisis descriptivo, identificar las entidades y relaciones de los datos y crear un diagrama. Tambien obtener estadísticas de los datos agrupados por esas entidades.

### Lectura del csv
"""

import os
import pandas as pd

df = pd.read_csv("datos_limpios.csv")

"""### Análisis estadistico descriptivo

Estadísticas descriptivas de los valores numericos y categoricos.
"""

df['Datetime'] = pd.to_datetime(df['Datetime'])

print("Estadisticas descriptivas de los valores numericos\n")
print(df.describe(include='number'))
print("\n" + "="*50 + "\n")
print("\nEstadisticas descriptivas de los valores categoricos\n")
print(df.describe(include='object'))

"""Asimetria y kurtosis:"""

print("Asimetria de los valores numericos\n")
print(df.skew(numeric_only=True))
print("\n" + "="*50 + "\n")
print("\nKurtosis de los valores numericos\n")
print(df.kurtosis(numeric_only=True))

"""Lo más notable del conjunto de datos sería el booking value que hace referencia al importe total del viaje, esto podría influir en los modelos estadisticos o machine learning.

### Identificación de las entidades y relaciones

Si checamos las columnas podremos ver las entidades que tendremos así como las relaciones.
"""

df.columns

"""En este caso podemos ver que varias cosas se relacionan con el "Booking", si tomamos eso como entidad principal, entonces lo que es Booking ID, Booking Status, Booking Value, Ride Distance, Datetime, Pickup Location, Drop Location, Avg VTAT, Avg CTAT, Driver Ratings y Customer Ratings. Las siguientes entidades tendrían un identificador único, tenemos a Customers con Customer ID, Vehicles con Vehicle Type y Payments con Payment Method.

Las relaciones quedarían:
* Customer-Booking. Un customer hace una Booking
* Booking-Vehicle. Una booking utiliza un Vehicle
* Booking-Payments. Una booking se paga con un Payment Method

### Estadisticas agrupadas por entidades

Si agrupamos los datos segun las entidades, estos serían de la siguiente forma: agrupación por los clientes, agrupación por los vehiculos y agrupación por reservas. Si pensamos en booking, no tiene tanto sentido, ya que de esta tabla es de donde sacamos los datos por el cual agrupamos las otras entidades.

Con la agrupación por clientes vemos cuantas reservas ha hecho, cuanto ha gastado y la calificación promedio. Con la agrupación por vehiculos y pagos vemos que tipo de vehiculo es el más utilizado y que metodo de pago es el más utilizado.
"""

customer_stats = df.groupby('Customer ID').agg(
    total_bookings=('Booking ID', 'count'),
    total_value=('Booking Value', 'sum'),
    avg_rating=('Customer Rating', 'mean')
).reset_index()

print("Estadísticas por Cliente:")
print(customer_stats.head())

print("\n" + "="*50 + "\n")

vehicle_stats = df.groupby('Vehicle Type').agg(
    total_bookings=('Booking ID', 'count'),
    avg_value=('Booking Value', 'mean'),
    avg_distance=('Ride Distance', 'mean')
).reset_index()

print("Estadísticas por Tipo de Vehículo:")
print(vehicle_stats)

print("\n" + "="*50 + "\n")

payment_stats = df.groupby('Payment Method').agg(
    total_bookings=('Booking ID', 'count'),
    avg_value=('Booking Value', 'mean')
).reset_index()

print("Estadísticas por Método de Pago:")
print(payment_stats)