# -*- coding: utf-8 -*-
"""Práctica9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-j1oofQ0pnkGIwgXjaFUEnWqQyyGCo9
"""

# Práctica 9: Text analysis: Create a word cloud from text data.
# Se usarán ambos dataset, el limpio que se ha usado en práctica pasadas y el que se uso en la práctica pasada
import pandas as pd

df = pd.read_csv("ncr_ride_bookings.csv")

df['Reason for cancelling by Customer'] = df['Reason for cancelling by Customer'].fillna('Not cancelled')
df['Cancelled Rides by Driver'] = df['Cancelled Rides by Driver'].fillna(0)
df['Cancelled Rides by Customer'] = df['Cancelled Rides by Customer'].fillna(0)
df['Driver Cancellation Reason'] = df['Driver Cancellation Reason'].fillna('Not cancelled')
df['Incomplete Rides'] = df['Incomplete Rides'].fillna(0)
df['Incomplete Rides Reason'] = df['Incomplete Rides Reason'].fillna('Not incomplete')
df['Booking Value'] = df['Booking Value'].fillna(0)
df['Ride Distance'] = df['Ride Distance'].fillna(0)
df['Driver Ratings'] = df['Driver Ratings'].fillna(0)
df['Customer Rating'] = df['Customer Rating'].fillna(0)
df['Avg CTAT'] = df['Avg CTAT'].fillna(0)
df['Avg VTAT'] = df['Avg VTAT'].fillna(0)
df['Payment Method'] = df['Payment Method'].fillna('Cancelled or incomplete ride')
df['is_cancelled'] = (df['Cancelled Rides by Customer'] == 1) | (df['Cancelled Rides by Driver'] == 1)
df['is_cancelled'] = df['is_cancelled'].astype(int)

df.info()

from wordcloud import WordCloud
import matplotlib.pyplot as plt

text_columns = df.select_dtypes(include='object').columns.tolist()
excluded_columns = ['Date', 'Time','is_cancelled']
text_columns = [col for col in text_columns if col not in excluded_columns]

for col in text_columns:
    text_data = df[col].fillna('')
    full_text = ' '.join(text_data.values)

    full_text.strip()
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(full_text)

    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.title(f'Word Cloud de {col}')
    plt.show()

all_text = ''

for col_name in text_columns:
    all_text += ' '.join(df[col_name].fillna('').astype(str).values) + ' '

wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud combinado')
plt.show()

# Datos limpios (Dataset usado normalmente)
df2 = pd.read_csv('datos_limpios.csv')
df2.info()

text_columns = df2.select_dtypes(include='object').columns.tolist()
excluded_columns = ['Datetime']
text_columns = [col for col in text_columns if col not in excluded_columns]

for col in text_columns:
    text_data = df2[col].fillna('')
    full_text = ' '.join(text_data.values)

    full_text.strip()
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(full_text)

    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.title(f'Word Cloud de {col}')
    plt.show()

all_text = ''

for col_name in text_columns:
    all_text += ' '.join(df2[col_name].fillna('').astype(str).values) + ' '

wordcloud = WordCloud(width=800, height=400, background_color='white').generate(all_text)

plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud combinado')
plt.show()