# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e_o8YQfxQ0OFghzM1gqjfV17uIBHgF4G

## Práctica 7: Data Clustering
"""

import pandas as pd

df = pd.read_csv("datos_limpios.csv")
df.head()

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans

# Separación de las columnas numericas y categoricas
categorical_features = ['Vehicle Type', 'Pickup Location', 'Drop Location', 'Payment Method']
numerical_features = ['Avg VTAT', 'Avg CTAT', 'Ride Distance', 'Customer Rating', 'Driver Ratings', 'Booking Value', 'Ride Distance', 'Customer Rating']

X = df.drop(['Booking ID', 'Booking Status', 'Customer ID', 'Datetime'], axis=1)

# Preprocesamiento de los datos usando Standard para datos numericos y OHE para datos categoricos
numerical_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

# Columna para aplicar las transformaciones
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)])

# Pipeline para preprocesar los datos y después aplicar lo que es kmeans
pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('kmeans', KMeans(n_clusters=3, random_state=42, n_init=10))])


pipeline.fit(X)
clusters = pipeline.predict(X)
df['Cluster'] = clusters
df.head()

# Gráficos
import matplotlib.pyplot as plt
import seaborn as sns

numerical_features = ['Avg VTAT', 'Avg CTAT', 'Ride Distance', 'Customer Rating', 'Driver Ratings', 'Booking Value']

for i in range(len(numerical_features)):
    for j in range(i + 1, len(numerical_features)):
        plt.figure(figsize=(10, 6))
        sns.scatterplot(data=df, x=numerical_features[i], y=numerical_features[j], hue='Cluster', palette='viridis')
        plt.title(f'Scatter plot of {numerical_features[i]} vs {numerical_features[j]} colored by cluster')
        plt.xlabel(numerical_features[i])
        plt.ylabel(numerical_features[j])
        plt.show()

  # La mejor gráfica que demostro bien lo del clustering fue la de Avg VTAT vs Driver Ratings

# Métrica para ver el rendimiento

from sklearn.metrics import silhouette_score

X_preprocessed = pipeline.named_steps['preprocessor'].transform(X)

score = silhouette_score(X_preprocessed, clusters)
print(f"Silhouette Score: {score:.3f}")