# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgfqDV7E4sPOsIqBAuKECMcj8AIVUTBg

## **PIA**

#### Dataset limpio
"""

import pandas as pd

df = pd.read_csv("datos_limpios.csv")
df.info()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,4))
sns.scatterplot(data=df, x='Ride Distance', y='Booking Value', color='orange')
plt.xlabel('Ride Distance')
plt.ylabel('Booking Value')
plt.show()

plt.figure(figsize=(8,4))
sns.scatterplot(data=df, x='Avg VTAT', y='Driver Ratings', color='red')
plt.xlabel('Avg VTAT')
plt.ylabel('Driver Ratings')
plt.show()

plt.figure(figsize=(8,4))
sns.scatterplot(data=df, x='Avg CTAT', y='Customer Rating')
plt.xlabel('Avg CTAT')
plt.ylabel('Customer Rating')
plt.show()

plt.figure(figsize=(8,4))
sns.scatterplot(data=df, x='Booking Value', y='Customer Rating', color='grey')
plt.xlabel('Booking Value')
plt.ylabel('Customer Rating')
plt.show()

df['Datetime'] = pd.to_datetime(df['Datetime'], errors='coerce')

df['Hora'] = df['Datetime'].dt.hour

tarifa = df.groupby('Hora')['Booking Value'].mean().reset_index()
tarifa.rename(columns={'Booking Value': 'Promedio Tarifa'}, inplace=True)

print(tarifa.to_markdown(index=False, floatfmt=".2f"))

"""#### Dataset original"""

df = pd.read_csv("ncr_ride_bookings.csv")
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], errors='coerce')
df.drop(['Date', 'Time'], axis=1, inplace=True)
df.info()

# sin limpieza de datos
plt.figure(figsize=(8,4))
sns.scatterplot(data=df, x='Ride Distance', y='Booking Value', color='orange')
plt.xlabel('Ride Distance')
plt.ylabel('Booking Value')
plt.show()

plt.figure(figsize=(8,4))
sns.scatterplot(data=df, x='Avg VTAT', y='Driver Ratings', color='red')
plt.xlabel('Avg VTAT')
plt.ylabel('Driver Ratings')
plt.show()

plt.figure(figsize=(8,4))
sns.scatterplot(data=df, x='Avg CTAT', y='Customer Rating')
plt.xlabel('Avg CTAT')
plt.ylabel('Customer Rating')
plt.show()

plt.figure(figsize=(8,4))
sns.scatterplot(data=df, x='Booking Value', y='Customer Rating', color='grey')
plt.xlabel('Booking Value')
plt.ylabel('Customer Rating')
plt.show()

df['Booking Value'] = df['Booking Value'].astype(str).str.replace('"', '', regex=False).str.strip()
df['Booking Value'] = pd.to_numeric(df['Booking Value'], errors='coerce')

df['Datetime'] = pd.to_datetime(df['Datetime'], errors='coerce')

df.dropna(subset=['Booking Value', 'Datetime'], inplace=True)

df['Hora'] = df['Datetime'].dt.hour

tarifa = df.groupby('Hora')['Booking Value'].mean().reset_index()
tarifa.rename(columns={'Booking Value': 'Promedio Tarifa'}, inplace=True)

print(tarifa.to_markdown(index=False, floatfmt=".2f"))

# con limpieza de datos
df = pd.read_csv("ncr_ride_bookings.csv")
df.isna().sum()

df['Reason for cancelling by Customer'] = df['Reason for cancelling by Customer'].fillna('Not cancelled')
df['Driver Cancellation Reason'] = df['Driver Cancellation Reason'].fillna('Not cancelled')
df['Incomplete Rides Reason'] = df['Incomplete Rides Reason'].fillna('Not incomplete')
df['Payment Method'] = df['Payment Method'].fillna('Cancelled or incomplete ride')

col_num = [
    'Cancelled Rides by Driver',
    'Cancelled Rides by Customer',
    'Incomplete Rides',
    'Booking Value',
    'Ride Distance',
    'Driver Ratings',
    'Customer Rating',
    'Avg CTAT',
    'Avg VTAT'
]

for col in col_num:
    df[col] = df[col].fillna(0)

df['Time'] = pd.to_datetime(df['Time'])
df['Date'] = pd.to_datetime(df['Date'])

df.info()

df['Hour'] = df['Time'].dt.hour

tarifa = df.groupby('Hour')['Booking Value'].mean().reset_index()
tarifa.rename(columns={'Booking Value': 'Promedio Tarifa'}, inplace=True)

print(tarifa.to_markdown(index=False, floatfmt=".2f"))

plt.figure(figsize=(12, 6))
plt.plot(tarifa['Hour'], tarifa['Promedio Tarifa'], marker='o', linestyle='-', color='#0066CC')
plt.title('Intento de demostrar tarifa dinámica')
plt.xlabel('Hora del Día (0 - 23)')
plt.ylabel('Tarifa Promedio (Booking Value)')
plt.xticks(range(24))
plt.grid(True, linestyle='--', alpha=0.6)

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

X, y = df.drop(columns=['Date','Time','Hour','Booking Status','Booking ID']), df['Booking Status']

le = LabelEncoder()
X = X.apply(lambda col: le.fit_transform(col.astype(str)) if col.dtypes == 'object' else col)
y = le.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")

decision_tree = DecisionTreeClassifier(max_depth=2)
decision_tree.fit(X_train, y_train)

y_pred = decision_tree.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")