# -*- coding: utf-8 -*-
"""Statistic Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ziqjz2BPc_umj0Z7qZLtNoyQMph8t0Kp

## Practica 4: Statistic Test

Demuestre que los datos etiquetados son diferentes mediante la ejecución de ANOVA + prueba T o prueba de Kruskall Wallis.

### Lectura del CSV
"""

import os
import pandas as pd

df = pd.read_csv("datos_limpios.csv")
df.info()

"""### Kruskall Wallis

Kruskal Wallis se usa para determinar si las medianas de dos o más grupos provienen de la misma distribución. No se usará ANOVA ya que esta prueba asume supuestos mientras que Kruskal Wallis no asume.

Entonces, nos podemos preguntar lo siguiente:
* ¿El valor de las reservas (Booking Value) cambia según el tipo de vehículo (Vehicle Type)?
* ¿La distancia recorrida (Ride Distancia) difiere del método de pago (Payment Method)?
* ¿El valor de las reservas (Booking Value) cambia según el mes (Datetime)?
"""

import pandas as pd
from scipy.stats import kruskal

def Interpretación(p):
  if p < 0.05:
    print("Hay diferencias significativas.")
  else:
    print("No hay diferencias significativas.")

cars = [car['Booking Value'].values for booking_value, car in df.groupby('Vehicle Type')]

stat, p = kruskal(*cars)
print('Statistics=%.3f, p=%.3f' % (stat, p))

Interpretación(p)

payment = [payment['Ride Distance'].values for ride_distance, payment in df.groupby('Payment Method')]

stat, p = kruskal(*payment)
print('Statistics=%.3f, p=%.3f' % (stat, p))

Interpretación(p)

df['Datetime'] = pd.to_datetime(df['Datetime'])
df['Mes'] = df['Datetime'].dt.month

date = [date['Booking Value'].values for booking_value, date in df.groupby('Mes')]

stat, p = kruskal(*date)
print('Statistics=%.3f, p=%.8f' % (stat, p))

Interpretación(p)